# Generated by Django 2.1 on 2018-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20180810_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosGerais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Comentarios Gerais',
            },
        ),
    ]
